### ISSUE TITLE
Running DPAM on a very large input - stuck on step 3

### ISSUE THREAD

**Issue by maiskhoury** [CongLabCode/DPAM#13]
Hi CongLab!,
I am curently trying to use you'r tool! 
I tried at first using it on a test directory with 15 proteins, I provided the json and pdb files as needed and it worked as it should.
now I am trying to run it on a very large input 20200 proteins and I keep getting stuck at step 3.
Is there a limit to the test size ? or is there any other issues with running dpam on such a large test? 
I keep running on this error (taken from the docker log file):
"Traceback (most recent call last):
  File "/opt/DPAM/scripts/run_step3.py", line 100, in <module>
    time.sleep(1)
NameError: name 'time' is not defined"

and before gettig this error I get:
- 15:57:38.177 INFO: Scoring 20000 HMMs using HMM-HMM Viterbi alignment
- - 16:01:17.523 INFO: Set premerge to 0! (premerge: 3 iteration: 2 hits.Size: 21829)
-  16:58:11.696 WARNING: database contains sequences that exceed maximum allowed size (maxres = 20001). Max sequence length can be increased with parameter -maxres.
 15:57:38.176 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 20000
 15:57:31.306 WARNING: Number of hits passing 2nd prefilter (reduced from 106056 to allowed maximum of 20000).
You can increase the allowed maximum using the -maxfilt <max> option.

step 1 and step 2 are done as they should I got the log files with done.

thankyou!

**Comment by jzhan6** [comment]
Apologies for the delayed response. It seems the error might have occurred because hhsearch did not complete for one of the queries. Identifying the specific query that caused hhsearch to fail would be beneficial in resolving this issue.

Best,
Jing Zhang

**Comment by maiskhoury** [comment]
Hi,
I got back to the same problem after succeeding a couple of times. I am still not knowing why I keep having this problem.
the last run that I tried and got stuck at step3 was trying to run DPAM on 100 proteins. 
step1 and step2 were done step 3 got stuck on the first protein of the list (as I saw on the log file).
this is what I got:

"12:01:02.395 INFO: Search results will be written to step1/RBP_sub_1/A0AV96.hhr

- 12:01:26.786 INFO: Searching 32053680 column state sequences.

- 12:01:27.200 INFO: step1/RBP_sub_1/A0AV96.fa is in A2M, A3M or FASTA format

- 12:01:27.201 INFO: Iteration 1

- 12:01:27.349 INFO: Prefiltering database

- 12:02:41.176 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 1227476

- 12:02:44.114 WARNING: Number of hits passing 2nd prefilter (reduced from 30085 to allowed maximum of 20000).
You can increase the allowed maximum using the -maxfilt <max> option.

- 12:02:46.197 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 20000

- 12:02:46.197 INFO: HMMs passed 2nd prefilter and not found in previous iterations : 20000

- 12:02:46.197 INFO: Scoring 20000 HMMs using HMM-HMM Viterbi alignment

- 12:02:49.609 INFO: Alternative alignment: 0

- 12:02:50.491 INFO: 2000 alignments done

- 12:02:51.284 INFO: 4000 alignments done

- 12:02:52.079 INFO: 6000 alignments done

- 12:02:52.844 INFO: 8000 alignments done

- 12:02:53.611 INFO: 10000 alignments done

- 12:02:54.702 INFO: 12000 alignments done

- 12:02:55.443 INFO: 14000 alignments done

- 12:02:56.301 INFO: 16000 alignments done

- 12:02:57.081 INFO: 18000 alignments done

- 12:02:57.870 INFO: 20000 alignments done

- 12:02:57.877 INFO: Alternative alignment: 1

- 12:03:06.238 INFO: 19949 alignments done

- 12:03:06.380 INFO: Alternative alignment: 2

- 12:03:15.862 INFO: 19159 alignments done

- 12:03:15.917 INFO: Alternative alignment: 3

- 12:03:21.687 INFO: 16428 alignments done

- 12:03:27.082 INFO: Premerge done

- 12:03:27.082 INFO: Realigning 500 HMM-HMM alignments using Maximum Accuracy algorithm

- 12:04:15.314 INFO: 2892 sequences belonging to 2892 database HMMs found with an E-value < 0.001

- 12:04:15.346 INFO: Number of effective sequences of resulting query HMM: Neff = 7.55723

- 12:04:16.097 INFO: Iteration 2

- 12:04:16.097 INFO: Set premerge to 0! (premerge: 3 iteration: 2 hits.Size: 2889)

- 12:04:16.260 INFO: Prefiltering database

Killed
Traceback (most recent call last):
  File "/opt/DPAM/scripts/run_step3.py", line 100, in <module>
    time.sleep(1)
NameError: name 'time' is not defined
"
what could be the problem with the hhsearch? 
thank you!
